baseURL = "https://jeiwan.net"
languageCode = "en"
title = "Going the distance"
# theme = "hugo-cactus-theme"
theme = "hugo-journal"
googleAnalytics = "UA-77183580-3"
disqusShortname = ""

[params]
  name = "Ivan Kuznetsov"
  description = "A blog about blockhains and smart contracts development"
  keywords = "bitcoin, ethereum, evm, smart contract, blockchain, programming, development, solidity, vyper"
  tagline = "A blog about blockhains and smart contracts development"
  bio = "Web Development - DevOps - Blockchain"

  authorEmail = "me@jeiwan.ru"
  githubUsername = "jeiwan"
  telegramUsername = "jeiwan"
  twitterUsername = "jeiwan7"

[author]
  name = "Ivan Kuznetsov"

[markup]
  [markup.highlight]
    noClasses=false
    style=""

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
