baseURL = "https://jeiwan.net"
languageCode = "en"
title = "Going the distance"
# theme = "hugo-cactus-theme"
theme = "hugo-journal"
googleAnalytics = "UA-77183580-3"
disqusShortname = ""

[params]
  name = "Ivan Kuznetsov"
  description = "Thoughts about web development, devops, and blockchain"
  tagline = "Thoughts about web development, devops, and blockchain"
  bio = "Web Development - DevOps - Blockchain"

  githubUsername = "jeiwan"
  telegramUsername = "jeiwan"
  twitterUsername = "jeiwan7"

[author]
  name = "Ivan Kuznetsov"